### ISSUE TITLE
serve is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mohd7469** [dest4/adblockradio-sdk#1]
how do i run serve command

![image](https://user-images.githubusercontent.com/12613564/44856749-9bd83380-ac87-11e8-9bb5-ab77c5e4e55b.png)

**Comment by dest4** [comment]
`npm install serve`

https://www.npmjs.com/package/serve

**Comment by mohd7469** [comment]
hey @dest4 thanks for your reply
 
you should add it to the **package.json** as a dependency : )

**Comment by dest4** [comment]
I have added `serve` as a devDependency https://github.com/adblockradio/adblockradio-sdk/commit/2e4260694810df115e97e610dc579fb624d92fa7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
