### ISSUE TITLE
sendPlaylist error

### ISSUE THREAD

**Issue by mohd7469** [dest4/adblockradio-sdk#2]
playlist update problem, from where its been asking for login

![image](https://user-images.githubusercontent.com/12613564/44859585-de9d0a00-ac8d-11e8-9b78-96ff1e0dbc72.png)

**Comment by dest4** [comment]
Hi, did you customize the token?

**Comment by mohd7469** [comment]
@dest4 nope, just had to put inside as it is

**Comment by dest4** [comment]
Please follow these instructions to use a valid token https://github.com/adblockradio/adblockradio-sdk#how-to-get-an-api-token
I know it is not very practical, but it's the best I could do given my available time.
